"""initial

Revision ID: 371b08d09394
Revises: 
Create Date: 2026-06-14 10:08:39.232798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371b08d09394'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_expenses_vendor_id'), 'expenses_vendor', ['id'], unique=False)
    op.create_table('expenses_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debit_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('txn_number', sa.String(length=100), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.CheckConstraint("(exclude = 1) OR (category != '' AND sub_category != '')", name='category_subcategory_required_if_not_excluded'),
    sa.ForeignKeyConstraint(['vendor_id'], ['expenses_vendor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_number')
    )
    op.create_index(op.f('ix_expenses_transaction_id'), 'expenses_transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_transaction_id'), table_name='expenses_transaction')
    op.drop_table('expenses_transaction')
    op.drop_index(op.f('ix_expenses_vendor_id'), table_name='expenses_vendor')
    op.drop_table('expenses_vendor')
    # ### end Alembic commands ###
