"""split transaction

Revision ID: 79dae7588d5d
Revises: 371b08d09394
Create Date: 2026-07-05 10:16:33.105731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79dae7588d5d"
down_revision: Union[str, Sequence[str], None] = "371b08d09394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses_transaction", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_transaction_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_expenses_transaction_parent_transaction",
            "expenses_transaction",
            ["parent_transaction_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses_transaction", schema=None) as batch_op:
        batch_op.drop_constraint("fk_expenses_transaction_parent_transaction", type_="foreignkey")
        batch_op.drop_column("parent_transaction_id")

    # ### end Alembic commands ###
